hardware:
  arduino_port: '/dev/tty.usbmodem101'  # or 'COM3' for Windows
  scope_address: 'USB0::0xF4EC::0xEE38::SDSMMFCD5R1059::INSTR'
  steps_per_mm:
    x: 100  # 0.01mm per step
    y: 100
    z: 100
  scope_settings:
    vertical_scale: 1.0       # V/div
    horizontal_scale: 2.5e-6  # s/div
    trigger_source: 'EXT'     # EXT or CH1
    trigger_slope: 'RISE'     # RISE or FALL
    trigger_mode: 'AUTO'      # AUTO or NORMAL
    trigger_coupling: 'AC'    # AC or DC
    channel_coupling: 'AC'    # AC or DC
    channel_position: 0       # vertical position

scan:
  type: '2d_yz'  # Options: 1d_x, 1d_y, 1d_z, 2d_xy, 2d_xz, 2d_yz
  dimensions:
    x: 0  # mm
    y: 20  # mm
    z: 20   # mm
    resolution: 0.5  # mm
  calibration_value: 0.3112  # V/MPa
  base_path: './scan_data'

