hardware:
  auto_scaling_enabled: true
  arduino_port: '/dev/tty.usbmodem101'  # or 'COMX' for Windows
  scope_address: 'USB0::0x0699::0x03A0::C014274::INSTR'
  steps_per_mm:
    x: 100  # 0.01mm per step
    y: 100
    z: 100
  scope_settings:
    trigger_level: 1.0
    vertical_scale: 1.0       # V/div
    horizontal_scale: 2.5e-6  # s/div
    trigger_source: 'EXT'     # EXT or CH1
    trigger_slope: 'RISE'     # RISE or FALL
    trigger_mode: 'AUTO'      # AUTO or NORMAL
    trigger_coupling: 'AC'    # AC or DC
    channel_coupling: 'AC'    # AC or DC
    channel_position: 0       # vertical position
    acquisition_mode: 'AVERAGE'  # SAMPLE, AVERAGE, PEAKDETECT
    average_count: 16        # 4, 16, 32, 64, 128 when mode is AVERAGE

scan:
  type: '1d_y'  # Options: 1d_x, 1d_y, 1d_z, 2d_xy, 2d_xz, 2d_yz
  dimensions:
    x: 0  # mm
    y: 2  # mm
    z: 0   # mm
    resolution: 0.5  # mm
  calibration_value: 0.3112  # V/MPa
  base_path: './scan_data'
  save_options:
    save_waveforms: true # Enable/disable saving of waveforms
    waveform_decimation: 1  # Decimation factor for waveforms ( 1 = all waveforms saved)

